//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Online.SecMgmt.PowerShell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Online.SecMgmt.PowerShell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than zero.
        /// </summary>
        internal static string AssertNumberPositiveInvalidError {
            get {
                return ResourceManager.GetString("AssertNumberPositiveInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number.
        /// </summary>
        internal static string AssertNumberPositiveInvalidPrefix {
            get {
                return ResourceManager.GetString("AssertNumberPositiveInvalidPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not set.
        /// </summary>
        internal static string AssertStringNotEmptyInvalidError {
            get {
                return ResourceManager.GetString("AssertStringNotEmptyInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        internal static string AssertStringNotEmptyInvalidPrefix {
            get {
                return ResourceManager.GetString("AssertStringNotEmptyInvalidPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change description : {0}.
        /// </summary>
        internal static string BreakingChangesAttributesChangeDescriptionMessage {
            get {
                return ResourceManager.GetString("BreakingChangesAttributesChangeDescriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0}
        ///.
        /// </summary>
        internal static string BreakingChangesAttributesDeclarationMessage {
            get {
                return ResourceManager.GetString("BreakingChangesAttributesDeclarationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Cmdlet : &apos;{0}&apos;
        /// - {1}.
        /// </summary>
        internal static string BreakingChangesAttributesDeclarationMessageWithCmdletName {
            get {
                return ResourceManager.GetString("BreakingChangesAttributesDeclarationMessageWithCmdletName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE : Go to {0} for steps to suppress this breaking change warning, and other information on breaking changes with the Security and Management Open PowerShell module..
        /// </summary>
        internal static string BreakingChangesAttributesFooterMessage {
            get {
                return ResourceManager.GetString("BreakingChangesAttributesFooterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaking changes in the cmdlet &apos;{0}&apos; :.
        /// </summary>
        internal static string BreakingChangesAttributesHeaderMessage {
            get {
                return ResourceManager.GetString("BreakingChangesAttributesHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note : This change will take effect on &apos;{0}&apos;.
        /// </summary>
        internal static string BreakingChangesAttributesInEffectByDateMessage {
            get {
                return ResourceManager.GetString("BreakingChangesAttributesInEffectByDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: The change is expected to take effect from the version &apos;{0}&apos;
        ///.
        /// </summary>
        internal static string BreakingChangesAttributesInEffectByVersion {
            get {
                return ResourceManager.GetString("BreakingChangesAttributesInEffectByVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cmdlet invocation changes :
        ///	Old Way : {0}
        ///	New Way : {1}.
        /// </summary>
        internal static string BreakingChangesAttributesUsageChangeMessageConsole {
            get {
                return ResourceManager.GetString("BreakingChangesAttributesUsageChangeMessageConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Connect-SecMgmtAccount to login.
        /// </summary>
        internal static string RunConnectSecMgmtAccount {
            get {
                return ResourceManager.GetString("RunConnectSecMgmtAccount", resourceCulture);
            }
        }
    }
}
